services:
  app:
    build:
      args:
        user: dani
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: simobe
    container_name: simobe-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - app_data:/var/www
    networks:
      - simobe

  nginx:
    image: nginx:alpine
    container_name: simobe-nginx
    restart: unless-stopped
    ports:
      - 8123:80
    volumes:
      - app_data:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - simobe

  db:
    image: mysql:8.0
    container_name: simobe-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - simobe
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: simobe-phpmyadmin
    links:
      - db
    restart: unless-stopped
    ports:
      - 8124:80
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    networks:
      - simobe

volumes:
    app_data:
      name: simobe_app_data
    db_data:
      name: simobe_db_data

networks:
  simobe:
    driver: bridge